# This file was automatically generated by sub\epyqlib\epyqlib\cli\generateversion.py
__version_build_time__ = "2023-09-21T15:25:28.626222"

__version__ = "0.0.0"
__sha__ = "e423b5ce978ca994dcc4b28fa4d250e18a22a2cd"
__revision__ = "e423b5ce978ca994dcc4b28fa4d250e18a22a2cd"
