name: CI

on:
  push:
    branches:
      - "**" #double star includes a '/'.  single star doesnt match a '/'
    tags:
      - "**" #double star includes a '/'.  single star doesnt match a '/'
  schedule:
    # Daily at 05:44
    - cron: '44 5 * * *'

defaults:
  run:
    shell: bash

env:
  PYTHON_VERSION: 3.7
  AWS_REGION: us-east-2

jobs:
  build:
    name: CI
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: recursive
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Install Poetry and Venv
        run: |
          python3 -m ensurepip
          python3 -m pip install --upgrade pip
          python3 -m pip install poetry
          poetry config virtualenvs.in-project true
          poetry config virtualenvs.path .

          #setup connection to aws server
          poetry config repositories.epc-power https://epc-power-us-${{ secrets.AWS_ACCOUNT_ID }}.d.codeartifact.us-east-2.amazonaws.com/pypi/epc-power/
          export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain epc-power-us --domain-owner ${{ secrets.AWS_ACCOUNT_ID }} --query authorizationToken --output text`
          echo "CODEARTIFACT_AUTH_TOKEN"
          poetry config http-basic.epc-power aws $CODEARTIFACT_AUTH_TOKEN
          poetry install
      - name: python commands
        run: |
          set -vx
          #poetry add decorator --source epc-power
          poetry run black --check --diff .
          poetry run builduipm
          poetry run builduiepyqlib
          poetry run poetry-dynamic-versioning

          poetry run python -c "import sys; print(sys.version)"

          poetry run pip freeze --all
          poetry run genbuildinfo "src/epcpm/__build.py"
          poetry run generateversion --distribution epcpm --out "src/epcpm/__version.py"

          poetry run pyinstaller pyinstaller.spec
          mv "dist/epcpm" "EPCPM_${GITHUB_RUN_ID}_${GITHUB_RUN_NUMBER}"
          7z a "EPCPM_${GITHUB_RUN_ID}_${GITHUB_RUN_NUMBER}.zip" "EPCPM_${GITHUB_RUN_ID}_${GITHUB_RUN_NUMBER}"


          mkdir artifacts
          mv *.zip artifacts/

          rm -rf dist
          poetry build
          cp dist/* artifacts/
          poetry run pytest epcpm.tests --pyargs
          ls -la
          pwd
          mv DELETEtox.zip dist/  #DELETE THIS LINE


      - name: Publish executable
        #only run if a new tag is created
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          #install twine
          pip install twine

          #poetry publish -u ${{ secrets.TWINE_USERNAME }} -p ${{ secrets.TWINE_PASSWORD }}
          #publish to aws
          ls dist/
          #poetry publish --repository epc-power
          #publish with twine
          #connect pip (do we need this?)
          aws codeartifact login --tool pip --repository epc-power --domain epc-power-us --domain-owner ${{ secrets.AWS_ACCOUNT_ID }}
          #aws twine login
          aws codeartifact login --tool twine --repository epc-power --domain epc-power-us --domain-owner ${{ secrets.AWS_ACCOUNT_ID }}
          #poetry run twine upload --repository codeartifact dist/* --repository-url https://epc-power-us-${{ secrets.AWS_ACCOUNT_ID }}.d.codeartifact.us-east-2.amazonaws.com/pypi/epc-power/ -u ${{ secrets.TWINE_USERNAME }} -p ${{ secrets.TWINE_PASSWORD }}
          twine upload --repository codeartifact dist/* --repository-url https://epc-power-us-${{ secrets.AWS_ACCOUNT_ID }}.d.codeartifact.us-east-2.amazonaws.com/pypi/epc-power/ -u ${{ secrets.TWINE_USERNAME }} -p ${{ secrets.TWINE_PASSWORD }}

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: pm
          path: |
            artifacts/*
