name: CI

on:
  push:
    branches:
      - "**" #double star includes a '/'.  single star doesnt match a '/'
    tags:
      - "**" #double star includes a '/'.  single star doesnt match a '/'
  schedule:
    # Daily at 05:44
    - cron: '44 5 * * *'

defaults:
  run:
    shell: bash

env:
  PYTHON_VERSION: 3.7

jobs:
  build:
    name: CI
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: recursive
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Poetry and Venv
        run: |
          python3 -m ensurepip
          python3 -m pip install --upgrade pip
          python3 -m pip install poetry
          poetry config virtualenvs.in-project true
          poetry config virtualenvs.path .

          #setup connection to aws server
          poetry config repositories.epc-power https://epc-power-us-890711758583.d.codeartifact.us-east-2.amazonaws.com/pypi/epc-power/
          export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain epc-power-us --domain-owner 890711758583 --query authorizationToken --output text`
          poetry config http-basic.epc-power aws eyJ2ZXIiOjEsImlzdSI6MTY0Nzk4MzAxNCwiZW5jIjoiQTEyOEdDTSIsInRhZyI6IkVrRmo0VGVPRGZFa3VVclB6TUZLMmciLCJleHAiOjE2NDgwMjYyMTQsImFsZyI6IkExMjhHQ01LVyIsIml2IjoiTFIxbXZjQ1E0XzQzS2RwRyJ9.eUHGFfHn7BvnJExkhilJgQ.zVK0uGsUlfGBJt-I.85g07geMhGkWVt736I9QasrDdle2jGMkhUrZgLW5K2iTf7z72HkNBpy1vshWRg8Pef4TVr-t6KnOUQHPvi1yQIvDHNsvt-FbtvOyGklxcKZiR33mPrfm3IDaSxtV40ywOqV-1pTCn-0GMROnl2qL0SeO4T41J3dpCXBL3jHokT43895s6OYYMw_wctHLs_J6MvMiXDkIkLHyZRuGaoinyBi6Bez7nQ83b-EWhNrcjypfnN1f3gjL4nZYcRKyxYI0dmd4AdPsw_Zx53tmcVU-802E8ioDQrRTJlvekiCRtWJCGTl4CBCTqMpDiYwxWR6k4Tzk6oQ7BdUm-OA67VxreFhY8Yo2JIYxGUk8qjH_4AF6oPHadCQeAl8hY2bbUQs9haJbni9Wdw7osJXuyzqJf_WiIA6MPdT3VpH2RfJaFdDGGqZh-HbsMMIX4umHhizne3cZcAg4OYBRnjx2mLJ4Pg-FRpHdHCc6QMOyluFWDKwOrqBYvMFhLmbja9JyPfYW6BI0DUmzVf6jfK4rnrvdI_PJJ5hpy1zAf34xnnN__zsGmk0UE34pNBEk7poa6lbZ-9eraKvEzXHRBYPu7scsPNEIqOvYN0D2UbhbKoVii4u8byYMPyKxkKJkRoNup2pvAOF9iIN6nbdv8kRXnw9oHyENBVlOvnSP5LfApTFPWyHSaxwCCiQgVkLrNMLydSa18tLw4f-oSrYoQTdEI0sy7EhIa3kPdZIhqJWnTRxCkZPTcSnGr5IIjw_gG6E_JuopxkdtoQy3ylgSqBHBZZaMJzozAk7dYAmglV9shehIbQa56_Gk7c1ht780fToIUPjGdD-G6r_uMlq7_t4eruj5ViVPBb0PsJ82_yXd62KBqa0Y2UYPwtpcOFkTwh_eApTEcm_Vpxr2mAQabsOmLJd_HGoFPhERy0Z9cVSxkyzDcd9XrNLX-g78ZQ.uCDc-G_QR5kagPFFwIisyw

          poetry install
      - name: python commands
        run: |
          set -vx
          poetry add pscad-ci --source epc-power
          poetry run black --check --diff .
          poetry run builduipm
          poetry run builduiepyqlib
          poetry run poetry-dynamic-versioning

          poetry run python -c "import sys; print(sys.version)"

          poetry run pip freeze --all
          poetry run genbuildinfo "src/epcpm/__build.py"
          poetry run generateversion --distribution epcpm --out "src/epcpm/__version.py"

          poetry run pyinstaller pyinstaller.spec
          mv "dist/epcpm" "EPCPM_${GITHUB_RUN_ID}_${GITHUB_RUN_NUMBER}"
          7z a "EPCPM_${GITHUB_RUN_ID}_${GITHUB_RUN_NUMBER}.zip" "EPCPM_${GITHUB_RUN_ID}_${GITHUB_RUN_NUMBER}"


          mkdir artifacts
          mv *.zip artifacts/

          rm -rf dist
          poetry build
          cp dist/* artifacts/

          poetry run pytest epcpm.tests --pyargs
          ls

      - name: Publish executable
        #only run if a new tag is created
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          #poetry publish -u ${{ secrets.TWINE_USERNAME }} -p ${{ secrets.TWINE_PASSWORD }}
          #publish to aws
          poetry publish --repository epc-power

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: pm
          path: |
            artifacts/*
